# Generated by Django 5.1.2 on 2024-11-07 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_start", models.DateTimeField(auto_now_add=True)),
                ("position", models.CharField(max_length=100)),
                (
                    "experience_level",
                    models.CharField(
                        choices=[("entry", "신입"), ("experienced", "경력")],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "interview",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="resume.interview",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InterviewResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video_path",
                    models.FileField(
                        blank=True, null=True, upload_to="interview_videos/"
                    ),
                ),
                (
                    "anxiety_graph_path",
                    models.FileField(
                        blank=True, null=True, upload_to="graphs/anxiety/"
                    ),
                ),
                (
                    "gaze_distribution_path",
                    models.FileField(blank=True, null=True, upload_to="graphs/gaze/"),
                ),
                (
                    "posture_distribution_path",
                    models.FileField(
                        blank=True, null=True, upload_to="graphs/posture/"
                    ),
                ),
                (
                    "voice_distribution_path",
                    models.FileField(blank=True, null=True, upload_to="graphs/voice/"),
                ),
                (
                    "expression_distribution_path",
                    models.FileField(
                        blank=True, null=True, upload_to="graphs/expression/"
                    ),
                ),
                ("filler_word_positions", models.JSONField(blank=True, default=list)),
                ("follow_up_questions", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "interview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="resume.interview",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="resume.question",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="resume/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resume",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="interview",
            name="resume",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interviews",
                to="resume.resume",
            ),
        ),
    ]
