# Generated by Django 5.1.2 on 2024-11-07 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="interviewresult",
            old_name="question",
            new_name="question_id",
        ),
    ]
