# Generated by Django 4.2.16 on 2024-11-11 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewresult",
            name="voice_ent_distribution_path",
            field=models.FileField(blank=True, null=True, upload_to="graph/voice_ent/"),
        ),
    ]
