# Generated by Django 4.2.16 on 2024-11-11 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0002_interviewresult_voice_ent_distribution_path"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interviewresult",
            name="voice_ent_distribution_path",
        ),
    ]
