# Generated by Django 5.1.2 on 2024-11-07 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0002_rename_question_interviewresult_question_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="interviewresult",
            old_name="question_id",
            new_name="question",
        ),
    ]
