# Generated by Django 4.2.16 on 2024-11-13 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0003_remove_interviewresult_voice_ent_distribution_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="audio_file",
            field=models.FileField(blank=True, null=True, upload_to="questions/audio/"),
        ),
    ]
