# Generated by Django 4.2.16 on 2024-11-14 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0004_question_audio_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewresult",
            name="answer_text",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
