# Generated by Django 4.2.16 on 2024-11-19 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0005_interviewresult_answer_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewresult",
            name="voice_top_indices",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
